global:
    scrape_interval: 5s
    external_labels:
        monitor: 'monitoring-example'

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'node-application'
      static_configs:
          - targets: ['app:4000']
